todoApp/core/views.py
from flask import Blueprint, render_template,url_for, redirect
from flask_login import current_user

core = Blueprint('core', __name__)

@core.route('/')
def home():

    return render_template('home.html')


@core.route('/about')
def about():
    
    return render_template('about.html')

todoApp/tasks/views.py
from flask import Flask, Blueprint,render_template,redirect,url_for, flash, request
from flask_login import login_required, current_user
from .forms import createTask
from todoApp.models import User, tasks
from todoApp import db
from datetime import date

task = Blueprint('task', __name__)


#All Task List
@task.route('/allTask')
def allTask():

    everyTask = tasks.query.all()
    admin = 'deepspraj'
    user1 = ''
    user2 = ''
    total = len(everyTask)
    
    return render_template('allTask.html', everyTask=everyTask, user1=user1, user2=user2, total=total, admin=admin)
    

#More Detailed Particular Task
@task.route('/separate')
@login_required
def separate():

    Id = request.args.get('tag')
    separateTask = tasks.query.get(Id)


    return render_template('separateTask.html', separateTask=separateTask)


#Delete Your Task
@task.route('/delete')
@login_required
def delete():

    Id = request.args.get('Id')
    separateTask = tasks.query.get(Id)
    db.session.delete(separateTask)
    db.session.commit()

    return redirect('allTask')


#Create New Task
@task.route('/createTask', methods=['GET', 'POST'])
@login_required
def newTask():

    form = createTask()

    if form.validate_on_submit():

        if form.dateOfTask.data >= date.today():
            
            taskNew = tasks(task = form.taskname.data, date = form.dateOfTask.data, userId=current_user.id)

            db.session.add(taskNew)
            db.session.commit()
            flash("Successfully Created task")

        return redirect(url_for('core.home'))
    

    return render_template('createTask.html', form = form)

todoApp/users/views.py
from flask import Blueprint, render_template, redirect, flash, url_for
from flask_login import logout_user, login_required, current_user, login_user
from todoApp.users.forms import *
from todoApp.models import User
from todoApp import db
from todoApp.core.views import core
from todoApp.error.errorHandlers import errorPages
from todoApp.users.otpHandler import otpGenerate
from cryptography.fernet import Fernet
from todoApp.users.otpHandler import otpGenerate
from werkzeug.security import generate_password_hash
from todoApp.users.profilePicHandler import addProfilePic

users = Blueprint('users', __name__)


#Account View
@users.route('/account')
@login_required
def account():

    return render_template('account.html', current_user=current_user)


#logout View
@users.route('/logout')
@login_required
def logoutUser():

    logout_user()
    
    return redirect(url_for('core.home'))


#login View
@users.route('/login', methods=['GET','POST'])
def loginUser():

    form = loginUserForm()

    if form.validate_on_submit():

        logUser = User.query.filter_by(username= form.username.data).first()

        if logUser.checkPassword(password=form.password.data) and logUser is not None:
            login_user(logUser)
            flash("User successfully logged in..!!")

            return redirect('account')

        if logUser is None:
	            return render_template('error.html')


    return render_template('login.html', form=form)



#Register View
@users.route('/register', methods=['GET', 'POST'])
def registerUser():

    form = registerUserForm()  

    if form.validate_on_submit():
        if (User.query.filter_by(email=form.email.data).first() is None) and (User.query.filter_by(username=form.username.data).first() is None):
            newRegister = otpGenerate()
            dataOtp = newRegister.otpGenerater(receiverEmail=form.email.data)

            key = Fernet.generate_key()

            with open('key.txt', 'wb') as safeKey:
                safeKey.write(key)

            f = Fernet(key)

            userName = f.encrypt(bytes(form.data['username'], 'utf-8'))
            emailId = f.encrypt(bytes(form.data['email'], 'utf-8'))
            passwordHash = f.encrypt(bytes(form.data['password'], 'utf-8'))
            otpEncrypt = f.encrypt(bytes(dataOtp, 'utf-8'))
            

            return redirect(url_for('users.otpVerify', ZOBmsZfI=userName, kOmpgatI=emailId, sDxPebsj=passwordHash, AXrBhKqy=otpEncrypt))

    return render_template('register.html', form=form)


#Otp Verification View
@users.route('/verifyOtp/<ZOBmsZfI>`<kOmpgatI>`<sDxPebsj>`<AXrBhKqy>', methods=['GET', 'POST'])
def otpVerify(ZOBmsZfI,kOmpgatI,sDxPebsj,AXrBhKqy):

    otpForm = otpVerification()

    if otpForm.validate_on_submit():
        
        with open('key.txt', 'rb') as safeKey:
            key = safeKey.read()

        key = str(key, 'utf-8')
        f = Fernet(key)

        username = f.decrypt(bytes(ZOBmsZfI, 'utf-8'))
        email = f.decrypt(bytes(kOmpgatI, 'utf-8'))
        password = f.decrypt(bytes(sDxPebsj, 'utf-8'))
        otp = f.decrypt(bytes(AXrBhKqy, 'utf-8'))

        usernameU = str(username, 'utf-8')
        emailU = str(email, 'utf-8')
        passwordU = str(password, 'utf-8')
        otp = str(otp, 'utf-8')

        if otp == str(otpForm.otpData.data):
            newUser = User(username=usernameU, email=emailU, password=passwordU)
            db.session.add(newUser)
            db.session.commit()

            return redirect (url_for('errorPages.success'))
        else:
            return redirect(url_for('errorPages.wrongOtp'))

    return render_template('verifyOtp.html', otpForm=otpForm)


@users.route('/changeDetails', methods=['GET', 'POST'])
@login_required
def changeDetails():

    updatePictureForm = updateProfilePicForm()
    passwordChange = updatePasswordForm()

    if updatePictureForm.validate_on_submit():
        if updatePictureForm.picture.data:
            pic = addProfilePic(updatePictureForm.picture.data)
            current_user.profileImage = pic
            db.session.commit()
            return redirect(url_for('users.account'))

    if passwordChange.validate_on_submit():
        username = current_user.username
        current = User.query.filter_by(username=username).first()
        current.passwordHashed = generate_password_hash(passwordChange.password.data)
        db.session.commit()
        return redirect(url_for('core.home'))
        
    return render_template('changeAccountDetails.html', updatePictureForm=updatePictureForm, passwordChange=passwordChange)


@users.route('/forgotPassword', methods=['GET', 'POST'])
def forgotPassword():

    passwordForm = forgotPasswordForm()

    if passwordForm.validate_on_submit():
        isUser = User.query.filter_by(email=passwordForm.email.data).first()
        if isUser is None:
            return redirect(url_for('users.registerUser'))

        else:
            token = forgotPass.dumps(passwordForm.email.data, salt=isUser.username)
            resetLink.linkGenerator(passwordForm.email.data,isUser.username, token)
            return redirect(url_for('users.loginUser'))

    return render_template('forgotPassword.html', passwordForm=passwordForm)

from todoApp import forgotPass
from todoApp.users.resetLinkHandler import resetLink
from itsdangerous import URLSafeTimedSerializer, SignatureExpired

@users.route('/forgotPassword/<email>/<token>/<username>', methods=['GET', 'POST'])
def newPassword (email, token, username):
    try:
        checkValidity = forgotPass.loads(token, salt=username, max_age=120)
        newPass = resetPasswordForm()
        if newPass.validate_on_submit():
            userPassword = User.query.filter_by(username=username).first()
            userPassword.passwordHashed = generate_password_hash(newPass.password.data)
            db.session.commit()
            return redirect(url_for('users.loginUser'))
            
        return render_template('newPassword.html', newPass=newPass, email=email)

    except SignatureExpired:
        return render_template('linkExpired.html')

todoApp/templates/allTask.html
{% extends "base.html"%}

{% block content %}


    
{% if total %}
<br>
<div class="container">
    <main class="grid">
        
    {% for count in everyTask %}
    <article>
        <img src="data:image/png;charset=utf-8;base64,{{count.user.profileImage}}" alt="imageofcreator" width="80%">
        <div class="text">
          <h4>Task : {{count.task}}</h4>
          <p class="card-text">Task date : {{count.date}}.</p>
                    <p class="card-text">Created by : {{count.user.username}}.</p>
                    <p class="card-text"><small class="text-muted">Date and Time of Creation : {{count.dateOfCreation}}</small></p>
                    {% set user1 = count.user.username  %}
                    {% set user2 = current_user.username  %}
                    {% if (user2 == admin) or (user1 == user2) %}
                        <p class="card-text"><small class="text-muted">For changes <a href="{{url_for('task.separate', tag=count.id)}}" class="card-link">click</a>.</small></p>
                    {% endif %}
        </div>
      </article>
            
    
    {% endfor %}

    
        </div>
        <br>
    <br>
    </div>
    
{% else %}
<div class="about">
    <div class="inner-about">
        <h1 class="display-4">No users have registered their task(s).</h1>
        <br>
        <br>
        {% if current_user.is_authenticated %}
        <p><a href="{{url_for('task.newTask')}}">Click</a> here to create a task.</p>
        {% else %}
        <p><a href="{{url_for('users.loginUser')}}">Click</a> here to login page.</p>
        {% endif %}
    </div>

{% endif %}

{% endblock %}

todoApp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="{{url_for('static',filename='logo.png')}}" type="image">
    <title>ToDo APP</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/main.css')}}">
    <script type="text/javascript" src="{{url_for('static', filename='javascript/main.js')}}"></script> 
    
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light barnav">
        <a class="navbar-brand" href="{{url_for('core.home')}}"><img width="20px" height="20px" src="{{url_for('static', filename='logo.png')}}" style="margin-top: -5%;"></a>
        <button class="navbar-toggler barnav" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="color:#000000;">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('task.allTask')}}">All Task<span class="sr-only"></span></a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('task.newTask')}}">Create Task<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('users.account')}}">Account<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('users.logoutUser')}}">Logout<span class="sr-only"></span></a>
            </li>
            {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('users.loginUser')}}">Login<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('users.registerUser')}}">Register<span class="sr-only"></span></a>
            </li>
            {% endif %}
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('core.about')}}">About<span class="sr-only"></span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="https://github.com/deepspraj">Raw Code<span class="sr-only">(current)</span></a>
            </li>
          
          </ul>
        </div>
      </nav>
      
        
              
        {% block content %}


        {% endblock %}
  
      

        
        <div class="modal fade" id="modalContactForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content" style="color:#000000">
            <div class="modal-header text-center">
              <h4 class="modal-title w-100 font-weight-bold">Feedback Form</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body mx-3">
              <div class="md-form mb-5">
                <i class="fas fa-user prefix grey-text"></i>
                <label data-error="wrong" data-success="right" for="form34">Your name</label>
                <input type="text" id="form34" class="form-control validate" placeholder="Ashish Munot">
              </div>
              <div class="md-form mb-5">
                <i class="fas fa-at" style="color:#000000"></i>
                <label data-error="wrong" data-success="right" for="form29" style="color:#000000">Your email</label>
                <input type="email" id="form29" class="form-control validate" placeholder="rupeshsanap@gmail.com">
              </div>
              <div class="md-form">
                <i class="fas fa-envelope"></i>
                <label data-error="wrong" data-success="right" for="form8" >Your message</label>
                <textarea type="text" id="form8" class="md-textarea form-control" rows="2" placeholder="Please provide us feedback for the best of I can."></textarea>
              </div>
            </div>
            <div class="modal-footer d-flex justify-content-center">
              
              <input type="submit" class="btn btn-unique" onsubmit="myFunction()">
            </div>
          </div>
        </div>
      </div>
    

  </body>
</html>

todoApp/templates/createTask.html
{% extends "base.html"%}

{% block content %}    



<div class="sidenav">
    <div class="login-main-text">
       <h2>Create<br> Your task here.</h2>
       
    </div>
 </div>
 <div class="main">
    <div class="col-md-6 col-sm-12">
       <div class="login-form">
          <form method="POST">
            {{form.hidden_tag()}}<br>
             <div class="form-group">
                {{form.taskname.label}}
                {{form.taskname(type="text", class="form-control", placeholder="Taskname")}}
             </div>
             <div class="form-group">
                {{form.dateOfTask.label}}
                {{form.dateOfTask(type="test", class="form-control", placeholder="Date (DD/MM/YYYY)")}}
             </div>
             {{form.submit(type="submit",class="btn btn-gray")}}
          </form>
       </div>
       <br>
       <br>
    </div>

 </div>











{% endblock %}

todoApp/templates/error.html
{% extends "base.html"%}

{% block content %}
<div class="about">
    <div class="inner-about">
        <h1 class="display-4">Sorry, User not registered.</h1>
        <br>
        <br>
        <p><a href="{{url_for('core.home')}}">Click</a> here to traverse back to home page.</p>
      
    </div>
    
    


{% endblock %}

todoApp/templates/forgotPassword.html
{% extends "base.html"%}

{% block content %}


<div class="sidenav">
    <div class="login-main-text">
       <h2>Forgot ?<br>Your Password</h2>
       <p><a href="{{url_for('users.loginUser')}}">Login</a> or <a href="{{url_for('users.registerUser')}}">Register</a> here to access.</p>
    </div>
 </div>
 <div class="main">
    <div class="col-md-6 col-sm-12">
       <div class="login-form">
          <form method="POST">
            {{passwordForm.hidden_tag()}}<br>
             <div class="form-group">
                {{passwordForm.email.label}}
                {{passwordForm.email(type="email", class="form-control", placeholder="Email")}}
             </div>
             {{passwordForm.submit(type="submit",class="btn btn-gray")}}
          </form>
          <br>
          <br>
            <p>Once submitted email id, reset link may take few seconds to get delivered.</p>
       </div>
       <br>
       <br>
    </div>

 </div>


{% endblock %}

todoApp/templates/home.html
{% extends "base.html"%}

{% block content %}





<div class="about">
    <div class="inner-about">
        <h1 class="display-4">Hi, {% if current_user.is_authenticated %}{{current_user.username}}..!!{% else %}Guest..!!{% endif %}</h1>
        <br><br><h3>Nice to see you!</h3>
      <p>I'm a student that writes code, creates bugs and sometimes frustrate for all the messed-up things.</p>
      {% if current_user.is_authenticated %}
      <p><a href="{{url_for('task.newTask')}}">Create</a> or <a href="{{url_for('task.allTask')}}">List</a> the tasks here.</p>
      {% else %}
      <p><a href="{{url_for('users.loginUser')}}">Login</a> or <a href="{{url_for('users.registerUser')}}">Register</a> here to access the web-app for free.</p>
      {% endif %}
      <p class="social">
        <a href="https://github.com/deepspraj">
          <i class="fab fa-github icon-18 mr-3"></i>
        </a>
      </p>
    </div>
  </div>
  
{% endblock %}

todoApp/templates/login.html
{% extends "base.html"%}

{% block content %}



<div class="sidenav">
    <div class="login-main-text">
       <h2>Application<br> Login Page</h2>
       <p><a href="{{url_for('users.loginUser')}}">Login</a> or <a href="{{url_for('users.registerUser')}}">Register</a> from here to access.</p>
    </div>
 </div>
 <div class="main">
    <div class="col-md-6 col-sm-12">
       <div class="login-form">
          <form method="POST">
            {{form.hidden_tag()}}<br>
             <div class="form-group">
                {{form.username.label}}
                {{form.username(type="text", class="form-control", placeholder="User Name")}}
             </div>
             <div class="form-group">
                {{form.password.label}}
                {{form.password(type="password", class="form-control", placeholder="Password")}}
                <br>
                <a href="{{url_for('users.forgotPassword')}}" style="float: right;">Forgot Password?</a>
                </div>
             {{form.submit(type="submit",class="btn btn-gray")}}
             
          </form>
            
       </div>
       <br>
       <br>
    </div>

 </div>














{% endblock %}

todoApp/templates/newPassword.html
{% extends "base.html"%}

{% block content %}


<div class="sidenav">
    <div class="login-main-text">
       <h2>Create...!!!<br>New Password</h2>
       <p><a href="{{url_for('users.loginUser')}}">Login</a> or <a href="{{url_for('users.registerUser')}}">Register</a> here to access.</p>
    </div>
 </div>
 <div class="main">
    <div class="col-md-6 col-sm-12">
       <div class="login-form">
          <form method="POST">
            {{newPass.hidden_tag()}}<br>
            <p>Please enter new password for {{email}}.</p>
            <div class="form-group">
                {{newPass.password.label}}
                {{newPass.password(type="password", class="form-control", placeholder="Password")}}
             </div>
             <div class="form-group">
                {{newPass.passwordConfirm.label}}
                {{newPass.passwordConfirm(type="password", class="form-control", placeholder="Confirm Password")}}
             </div>
             {{newPass.submit(type="submit", class="btn btn-gray")}}           
       </div>
       <br>
       <br>
    </div>

 </div>


{% endblock %}

todoApp/templates/register.html
{% extends "base.html"%}

{% block content %}


    <div class="sidenav">
        <div class="login-main-text">
           <h2>Application<br> Register Page</h2>
           <p><a href="{{url_for('users.loginUser')}}">Login</a> or <a href="{{url_for('users.registerUser')}}">Register</a> from here to access.</p>
           <p><b>Note:</b><br>
            1.) After registration please do upload your image or any random image for distinguishing the tasks.<br>
            2.) Please don't upload 2k or 4k images.</p>
        </div>
     </div>
     <div class="main">
        <div class="col-md-6 col-sm-12">
           <div class="login-form">
              <form method="POST">
                {{form.hidden_tag()}}<br>
                 <div class="form-group">
                    {{form.username.label}}
                    {{form.username(type="text", class="form-control", placeholder="User Name")}}
                 </div>
                 <div class="form-group">
                    {{form.email.label}}
                    {{form.email(type="email", class="form-control", placeholder="Email id")}}
                 </div>
                 <div class="form-group">
                    {{form.password.label}}
                    {{form.password(type="password", class="form-control", placeholder="Password")}}
                 </div>
                 <div class="form-group">
                    {{form.passwordConfirm.label}}
                    {{form.passwordConfirm(type="password", class="form-control", placeholder="Confirm Password")}}
                 </div>
                 {{form.submit(type="submit", class="btn btn-gray", onclick="ConfirmForm()")}}
                 
              </form>
             
           </div>
           <br>
       <br>
        </div>
    



        
     </div>
    



 
 <!-- Modal -->
 <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
     <div class="modal-content">
       <div class="modal-header">
         <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
       </div>
       <div class="modal-body">
         ...
       </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
         <button type="button" class="btn btn-primary">Save changes</button>
       </div>
     </div>
   </div>
 </div>





{% endblock %}

todoApp/templates/separateTask.html
{% extends "base.html"%}

{% block content %}

  <div class="about">
    <div class="inner-about">
      <div class="taskDetails" style="float:left;">
      <p>Task Name : {{separateTask.task}}</p>
      <p>Task Date : {{separateTask.date}}</p>
      <p>Date and Time of Creation : {{separateTask.dateOfCreation}}</p>
      <p>Created by : {{separateTask.user.username}}</p>
      <br>
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
        Delete Task
      </button>
    </div>
    
    
    <div class="taskerImage">
      <img src="data:image/png;charset=utf-8;base64,{{current_user.profileImage}}" alt="imageofcreator" style="float:right; width: 25%; height: 25%; border-radius: 50%;">
    </div>
     
      
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel" style="color: #000;">Confirmation</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" style="color: #000;">
              <b>Are you sure {{current_user.username}} to delete the task ? </b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-warning" data-dismiss="modal">Nope</button>
              <a href="{{url_for('task.delete', Id=separateTask.id)}}"><button type="button" class="btn btn-danger"1>Delete</button></a>
            </div>
          </div>
        </div>
      </div>


</div>

{% endblock %}

todoApp/templates/success.html
{% extends "base.html"%}

{% block content %}
<div class="about">
    <div class="inner-about">
        <h1 class="display-4">Successfully Verified.</h1>
        <br>
        <br>
        <p><a href="{{url_for('users.loginUser')}}">Click</a> here to traverse to login page.</p>
      
    </div>
    
    


{% endblock %}

todoApp/templates/verifyOtp.html
{% extends "base.html"%}

{% block content %}

    
    
    
    <div class="sidenav">
        <div class="login-main-text">
           <h2>Application<br>OTP verification Page</h2>
           <p><a href="{{url_for('users.loginUser')}}">Login</a> or <a href="{{url_for('users.registerUser')}}">Register</a> from here to access.</p>
        </div>
     </div>
     <div class="main">
        <div class="col-md-6 col-sm-12">
           <div class="login-form">
              <form method="POST">
                {{otpForm.hidden_tag()}}<br>
                 <div class="form-group">
                    {{otpForm.otpData.label}}
                    {{otpForm.otpData(type="password", class="form-control", placeholder="OTP")}}
                 </div>
                 
                 {{otpForm.submit(type="submit",class="btn btn-gray")}}
                 
              </form>
              <br>
               <br>
            <p>Once submitted email id, otp may take few seconds to get delivered.</p>
                
           </div>
           <br>
           <br>
        </div>
    
     </div>
    


{% endblock %}

todoApp/templates/wrongOtp.html
{% extends "base.html"%}

{% block content %}
<div class="about">
    <div class="inner-about">
        <h1 class="display-4">Sorry, the otp is wrong.</h1>
        <br>
        <br>
        <p><a href="{{url_for('core.home')}}">Click</a> here to traverse back to home page.</p>
      
    </div>
    
    


{% endblock %}